(setq fizz-buzz '((3 . "Fizz")
                  (5 . "Buzz")
                  (7 . "Bazz")))

(defun getFizzBuzzString (i)
  (let ((result ""))
    (dolist (entry fizz-buzz)
      (let ((key (car entry))
            (value (cdr entry)))
        (when (= (mod i key) 0)
          (setq result (concatenate 'string result value)))))
    (if (string= result "")
        (return-from getFizzBuzzString i)
        (return-from getFizzBuzzString result))))

(loop for i from 1 to 30 do ( format t "~d~%" (getFizzBuzzString i)))
